// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AcknowledgeShutdown() {
    let $resultPromise = /** @type {any} */($Call.ByID(3290647209));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function LoadState() {
    let $resultPromise = /** @type {any} */($Call.ByID(1807414826));
    return $resultPromise;
}

/**
 * @returns {Promise<$models.UserSettings | null> & { cancel(): void }}
 */
export function LoadUserSettings() {
    let $resultPromise = /** @type {any} */($Call.ByID(3300701507));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} jsonBlob
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveState(jsonBlob) {
    let $resultPromise = /** @type {any} */($Call.ByID(524165709, jsonBlob));
    return $resultPromise;
}

/**
 * @param {$models.UserSettings | null} settings
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveUserSettings(settings) {
    let $resultPromise = /** @type {any} */($Call.ByID(555307638, settings));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.UserSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
