// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function AcknowledgeShutdown() {
    return $Call.ByID(3290647209);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LoadState() {
    return $Call.ByID(1807414826);
}

/**
 * @returns {$CancellablePromise<$models.UserSettings | null>}
 */
export function LoadUserSettings() {
    return $Call.ByID(3300701507).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} jsonBlob
 * @returns {$CancellablePromise<void>}
 */
export function SaveState(jsonBlob) {
    return $Call.ByID(524165709, jsonBlob);
}

/**
 * @param {$models.UserSettings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveUserSettings(settings) {
    return $Call.ByID(555307638, settings);
}

// Private type creation functions
const $$createType0 = $models.UserSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
