// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../net/http/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as url$0 from "../../../net/url/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {http$0.Request | null} req
 * @param {string | null} environmentID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AttachCookiesToRequest(req, environmentID) {
    let $resultPromise = /** @type {any} */($Call.ByID(48298745, req, environmentID));
    return $resultPromise;
}

/**
 * @param {url$0.URL | null} reqURL
 * @param {http$0.Response | null} resp
 * @param {string | null} environmentID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function CaptureResponseCookies(reqURL, resp, environmentID) {
    let $resultPromise = /** @type {any} */($Call.ByID(2599848187, reqURL, resp, environmentID));
    return $resultPromise;
}

/**
 * @param {string | null} environmentID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ClearAllCookies(environmentID) {
    let $resultPromise = /** @type {any} */($Call.ByID(518917970, environmentID));
    return $resultPromise;
}

/**
 * @param {string} domain
 * @param {string | null} environmentID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ClearCookiesForDomain(domain, environmentID) {
    let $resultPromise = /** @type {any} */($Call.ByID(4034706406, domain, environmentID));
    return $resultPromise;
}

/**
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteCookie(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(166643266, id));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Init() {
    let $resultPromise = /** @type {any} */($Call.ByID(2109151281));
    return $resultPromise;
}

/**
 * @param {string | null} environmentID
 * @returns {Promise<$models.Cookie[]> & { cancel(): void }}
 */
export function ListCookies(environmentID) {
    let $resultPromise = /** @type {any} */($Call.ByID(1028475926, environmentID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<number> & { cancel(): void }}
 */
export function PurgeExpiredCookies() {
    let $resultPromise = /** @type {any} */($Call.ByID(473737338));
    return $resultPromise;
}

/**
 * @param {$models.CookieInput} input
 * @returns {Promise<$models.Cookie> & { cancel(): void }}
 */
export function UpsertCookie(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(4205529402, input));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {$models.CookieInput[]} inputs
 * @returns {Promise<$models.Cookie[]> & { cancel(): void }}
 */
export function UpsertCookies(inputs) {
    let $resultPromise = /** @type {any} */($Call.ByID(3835977195, inputs));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.Cookie.createFrom;
const $$createType1 = $Create.Array($$createType0);
