// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * @param {string} filename
 * @returns {Promise<void> & { cancel(): void }}
 */
export function CreateEnvFile(filename) {
    let $resultPromise = /** @type {any} */($Call.ByID(1059427170, filename));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function InitEnvarWatch() {
    let $resultPromise = /** @type {any} */($Call.ByID(666796096));
    return $resultPromise;
}

/**
 * @param {string} filename
 * @returns {Promise<string> & { cancel(): void }}
 */
export function ReadEnvFile(filename) {
    let $resultPromise = /** @type {any} */($Call.ByID(1938492522, filename));
    return $resultPromise;
}

/**
 * @param {string} filename
 * @param {string} content
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveEnvFile(filename, content) {
    let $resultPromise = /** @type {any} */($Call.ByID(2467134833, filename, content));
    return $resultPromise;
}

/**
 * @returns {Promise<json$0.RawMessage> & { cancel(): void }}
 */
export function ScanEnvars() {
    let $resultPromise = /** @type {any} */($Call.ByID(1532249697));
    return $resultPromise;
}
