// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function CreateEnvFile(filename) {
    return $Call.ByID(1059427170, filename);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InitEnvarWatch() {
    return $Call.ByID(666796096);
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function ReadEnvFile(filename) {
    return $Call.ByID(1938492522, filename);
}

/**
 * @param {string} filename
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveEnvFile(filename, content) {
    return $Call.ByID(2467134833, filename, content);
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ScanEnvars() {
    return $Call.ByID(1532249697);
}
