// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} jsonContent
 * @returns {$CancellablePromise<void>}
 */
export function ImportPostmanCollection(jsonContent) {
    return $Call.ByID(2450317308, jsonContent);
}

/**
 * @param {string} rawExportJSON
 * @returns {$CancellablePromise<void>}
 */
export function ParsePostmanV21Collection(rawExportJSON) {
    return $Call.ByID(1476867943, rawExportJSON);
}
