// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {string} jsonContent
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ImportPostmanCollection(jsonContent) {
    let $resultPromise = /** @type {any} */($Call.ByID(2450317308, jsonContent));
    return $resultPromise;
}

/**
 * @param {string} rawExportJSON
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ParsePostmanV21Collection(rawExportJSON) {
    let $resultPromise = /** @type {any} */($Call.ByID(1476867943, rawExportJSON));
    return $resultPromise;
}
