// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("parentCollectionId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parentCollectionId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const DBTarget = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DBMain: "main",
};

export class Keybind {
    /**
     * Creates a new Keybind instance.
     * @param {Partial<Keybind>} [$$source = {}] - The source object to create the Keybind.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["command"] = null;
        }
        if (!("bind" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bind"] = null;
        }
        if (!("prettyName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["prettyName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keybind instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Keybind}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Keybind(/** @type {Partial<Keybind>} */($$parsedSource));
    }
}

export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["collectionId"] = null;
        }
        if (!("collectionName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["collectionName"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["name"] = null;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["description"] = null;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["method"] = null;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["url"] = null;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["headers"] = null;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["body"] = null;
        }
        if (!("bodyType" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bodyType"] = null;
        }
        if (!("bodyFormat" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bodyFormat"] = null;
        }
        if (!("auth" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["auth"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["sortOrder"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Response | null | undefined}
             */
            this["response"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField13_0($$parsedSource["response"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headers"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("runtimeMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runtimeMS"] = 0;
        }
        if (!("requestID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestID"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["createdAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

export class SQLRequest {
    /**
     * Creates a new SQLRequest instance.
     * @param {Partial<SQLRequest>} [$$source = {}] - The source object to create the SQLRequest.
     */
    constructor($$source = {}) {
        if (!("db" in $$source)) {
            /**
             * @member
             * @type {DBTarget}
             */
            this["db"] = DBTarget.$zero;
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {any[]}
             */
            this["params"] = [];
        }
        if (!("maxRows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRows"] = 0;
        }
        if (!("readOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SQLRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField2_0($$parsedSource["params"]);
        }
        return new SQLRequest(/** @type {Partial<SQLRequest>} */($$parsedSource));
    }
}

export class SQLResponse {
    /**
     * Creates a new SQLResponse instance.
     * @param {Partial<SQLResponse>} [$$source = {}] - The source object to create the SQLResponse.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_: string]: any }[] | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rowsAffected"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastInsertId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SQLResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new SQLResponse(/** @type {Partial<SQLResponse>} */($$parsedSource));
    }
}

export class UserSettings {
    /**
     * Creates a new UserSettings instance.
     * @param {Partial<UserSettings>} [$$source = {}] - The source object to create the UserSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("defaultEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultEnv"] = "";
        }
        if (!("enableAnimations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableAnimations"] = false;
        }
        if (!("responseHistoryTTL" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["responseHistoryTTL"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSettings(/** @type {Partial<UserSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
