// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("parentCollectionId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parentCollectionId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

export class Cookie {
    /**
     * Creates a new Cookie instance.
     * @param {Partial<Cookie>} [$$source = {}] - The source object to create the Cookie.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["environmentId"] = null;
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("hostOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hostOnly"] = false;
        }
        if (!("httpOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["httpOnly"] = false;
        }
        if (!("secure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secure"] = false;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["session"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["sameSite"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["expiresAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["extensions"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["lastAccessedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cookie instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cookie}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField12_0($$parsedSource["extensions"]);
        }
        return new Cookie(/** @type {Partial<Cookie>} */($$parsedSource));
    }
}

export class CookieInput {
    /**
     * Creates a new CookieInput instance.
     * @param {Partial<CookieInput>} [$$source = {}] - The source object to create the CookieInput.
     */
    constructor($$source = {}) {
        if (!("environmentId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["environmentId"] = null;
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("hostOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hostOnly"] = false;
        }
        if (!("httpOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["httpOnly"] = false;
        }
        if (!("secure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secure"] = false;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["session"] = false;
        }
        if (!("sameSite" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["sameSite"] = null;
        }
        if (!("expiresAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["expiresAt"] = null;
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CookieInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CookieInput}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField11_0($$parsedSource["extensions"]);
        }
        return new CookieInput(/** @type {Partial<CookieInput>} */($$parsedSource));
    }
}

export class Keybind {
    /**
     * Creates a new Keybind instance.
     * @param {Partial<Keybind>} [$$source = {}] - The source object to create the Keybind.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["command"] = null;
        }
        if (!("bind" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bind"] = null;
        }
        if (!("prettyName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["prettyName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keybind instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Keybind}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Keybind(/** @type {Partial<Keybind>} */($$parsedSource));
    }
}

export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["collectionId"] = null;
        }
        if (!("collectionName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["collectionName"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["name"] = null;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["description"] = null;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["method"] = null;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["url"] = null;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["headers"] = null;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["body"] = null;
        }
        if (!("bodyType" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bodyType"] = null;
        }
        if (!("bodyFormat" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["bodyFormat"] = null;
        }
        if (!("auth" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["auth"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["sortOrder"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Response | null | undefined}
             */
            this["response"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField13_0($$parsedSource["response"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headers"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("runtimeMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runtimeMS"] = 0;
        }
        if (!("requestID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestID"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

export class UserSettings {
    /**
     * Creates a new UserSettings instance.
     * @param {Partial<UserSettings>} [$$source = {}] - The source object to create the UserSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("defaultEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultEnv"] = "";
        }
        if (!("enableAnimations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableAnimations"] = false;
        }
        if (!("responseHistoryTTL" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["responseHistoryTTL"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSettings(/** @type {Partial<UserSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Response.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
