// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function FetchUserKeybinds() {
    return $Call.ByID(1039586992);
}

/**
 * @param {$models.Keybind[]} keybinds
 * @returns {$CancellablePromise<void>}
 */
export function UpdateUserKeybinds(keybinds) {
    return $Call.ByID(935276461, keybinds);
}
